covithon/Go-Corona-Go/video_conference/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_scope :company do
    root to: 'devise/sessions#new'
  end

  devise_for :companies, :skip => [:registration], controllers: { confirmations: 'confirmation' }
  as :company do
    get 'companies/new' => 'companies#new', :as => 'new_company_registration'
    post 'companies' => 'companies#create', :as => 'company_registration'
  end

  get 'new_meeting', to: 'companies#new_meeting'
  resources :companies, only: [:show]

  resources :video_conferences, only: [:create]
end

covithon/Go-Corona-Go/video_conference/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

covithon/Go-Corona-Go/video_conference/app/models/company.rb
class Company < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :validatable
  # :registerable, :recoverable, :rememberable, 
  has_many :subscriptions
  validates :name, :email, presence: true
  accepts_nested_attributes_for :subscriptions
end

covithon/Go-Corona-Go/video_conference/app/models/meet.rb
# frozen_string_literal: true

class Meet < ApplicationRecord
  MEET_DOMAIN = "meet.jit.si"

  validates :room, presence: true
  validates :room, uniqueness: true
end

covithon/Go-Corona-Go/video_conference/app/models/subscription.rb
class Subscription < ApplicationRecord
  validates :type, presence: true
  validates :type, inclusion: {in: ['Gold', 'Silver','Bronze']}
  belongs_to :company
end

covithon/Go-Corona-Go/video_conference/app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
end

covithon/Go-Corona-Go/video_conference/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate!

  def authenticate!
    :authenticate_user! if company_signed_in?
  end

  def after_sign_in_path_for(resource)
    stored_location_for(resource) || new_meeting_path
  end

  def after_sign_out_path_for(resource_or_scope)
    root_path
  end
end

covithon/Go-Corona-Go/video_conference/app/controllers/companies_controller.rb
# frozen_string_literal: true

class CompaniesController < ApplicationController
  skip_before_action :authenticate!, :only => [:new, :create] 

  def new
    @company = Company.new
    @company.subscriptions.build
  end
  
  def create
    @company = Company.new(company_params)
    if @company.save
      redirect_to new_company_session_path
    else
      redirect_to new_company_registration_path
    end
  end

  def new_meeting
  end

  def show
    Meet.create(room: params['company']['name'])
  end

  private

  def company_params
    params.require(:company).permit(:name, :email, :password, :password_confirmation,
                                    subscriptions_attributes: [:type])
  end
end

covithon/Go-Corona-Go/video_conference/app/controllers/video_conferences_controller.rb
# frozen_string_literal: true

class VideoConferencesController < ApplicationController
  skip_before_action :authenticate!,  :verify_authenticity_token

  def create

    if (user = User.find_or_create_by(conference_params)) && \
      (video_conference = Meet.create(room: SecureRandom.alphanumeric, password: SecureRandom.hex(4)))

      render(
        json: {
          data: {
            video_conference: {
              room: video_conference.room,
              domain: Meet::MEET_DOMAIN,
              password: video_conference.password,
              user: {
                name: user.name,
                email: user.email,
                avatar_url: user.avatar_url
              }
            }
          },
          message: "Successfully Created Video Conference" },
        status: :ok
      )
    else
      render json: { data: {}, errors: [user.errors.messages, video_conference.errors.messages], message: "Failed to create videoconfernce" }, status: :unprocessable_entity
    end
  end

  private

  def conference_params
    params.require(:user).permit(:name, :email, :avatar_url)
  end
end

covithon/Go-Corona-Go/video_conference/app/helpers/application_helper.rb
module ApplicationHelper
end

covithon/Go-Corona-Go/video_conference/app/views/companies/new.html.haml
%body.body-class
  %center
    #login.pt-5
      .container
        #login-row.row.justify-content-center.align-items-center
          #login-column.col-md-6
            #login-box.col-md-8
              = semantic_form_for(@company, method: :post, url: company_registration_path )do |f|
                %h3.text-center.text-white
                  %b Create Account
                %br
                  .form-group
                    .col.s12
                      %input#name.form-control{:name => "company[name]", :placeholder => " Company Name", :required => "", :type => "text"}/
                    %br
                    .col.s12
                      = f.email_field :email, autofocus: true, autocomplete: "email", id: 'username', class: 'form-control', placeholder: 'Email'
                  .form-group
                    .col.s12
                      = f.password_field :password, autocomplete: "current-password", id: 'password', class: 'form-control', placeholder: 'Password'
                    %br
                    .col.s12
                      = f.password_field :password_confirmation, id: 'password', class: 'form-control', :placeholder => "Confirm Password"
                      %br

                  .subscriptions
                    %h5.text-center.text-white Select Subscription Type:
                    = f.semantic_fields_for :subscriptions do |a|
                      .form-group
                        .col.s12
                          %select.form-control{name: "subscriptions_attributes[type]"}
                            %option Gold
                            %option Silver
                            %option Bronze

                      .actions.text-center
                        = f.submit 'Submit', class: "btn btn-primary"
                        = link_to "Back", new_company_session_path, :class=> "btn btn-success"

covithon/Go-Corona-Go/video_conference/app/views/companies/new_meeting.html.haml
%br
%br
%section.main-content
  .container
    %br
    %h2.text-center Start Meeting
    %br
    = form_tag(company_path(current_company.id), method: :get) do
      %input{ :type => "hidden", :name => 'company[email]', value: current_company.email}
      %table.table
        %tbody
          %tr
            .form-group
              %th.text-center{:scope => "row"}
                %label{:for => "meetingName"} Email
              %td
                %input#meetingEmail.form-control{ :type => "text", disabled: true, value: current_company.email}

          %tr
            .form-group
              %th.text-center{:scope => "row"}
                %label{:for => "meetingName"} Name
              %td
                %input#meetingName.form-control{:placeholder => "Meeting Name", :type => "text", :name => 'company[name]'}
          %tr
            .form-group
              %th.text-center{:scope => "row"}
                %label{:for => "meetingPassword"} Password
              %td
                %input#meetingPassword.form-control{:placeholder => "Meeting Password", :type => "password", :name => 'company[password]'}

          %tr
            %td.text-center{:colspan => "2"}
              %button.btn.btn-primary{:type => "submit"} Start
              %button.btn.btn-primary{:type => "submit"} Join

covithon/Go-Corona-Go/video_conference/app/views/companies/show.html.haml
%br

#meet

:javascript
  $(document).ready(function() {
    var name = "#{params['company']['name']}"
    var email = "#{params['company']['email']}"
    var password = "#{params['company']['password']}"
    getMeetingDetails(name, email, password);
  });

covithon/Go-Corona-Go/video_conference/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VideoConference</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src='https://meet.jit.si/external_api.js'></script>
  </head>
  <body>
    <nav class='navbar navbar-light nav-bar-color'>
      <img src='/assets/Josh_logo.png' alt='company logo' width='155px'>
      <a class='navbar-brand text-white' href='/companies/sign_in'> Video Conference</a>
      <% if company_signed_in? %>
        <%= link_to 'Logout', destroy_company_session_path, method: :delete, class: 'navbar-brand text-white' %>
      <% end %>
    </nav>
    <%= yield %>
  </body>
</html>